"""empty message

Revision ID: 4dc29e448ea7
Revises: c7ca98cabec6
Create Date: 2017-03-31 14:09:13.053632

"""

# revision identifiers, used by Alembic.
revision = '4dc29e448ea7'
down_revision = 'c7ca98cabec6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'longitude')
    op.drop_column('companies', 'latitude')
    # ### end Alembic commands ###
